apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
   name: prometheus-dev
spec:
#  serviceAccountName: prometheus
 serviceMonitorSelector:
   matchLabels:
     env: dev
 resources:
   requests:
     memory: 200Mi
     cpu: 2